name: Close informational

on:
  issues:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'Informational' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Close change record
        run: gh issue close ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
